import { JobStatus, Prisma } from "@prisma/client";

export type SeedJobInput = Prisma.JobCreateInput;

export const seedJobs: SeedJobInput[] = [
  {
    title: "AI Product Operator",
    slug: "ai-product-operator",
    team: "Applied AI",
    location: "New York, NY",
    workModel: "Hybrid",
    level: "Mid-Senior",
    description:
      "Own the day-to-day operating cadence for AI-assisted product workflows. This role sits between product, operations, and data teams to keep experiments moving from prototype to reliable internal tooling.",
    responsibilities: [
      "Run the weekly operating rhythm for AI feature launches and internal adoption.",
      "Translate ambiguous process gaps into scoped workflow improvements and operator playbooks.",
      "Partner with product, recruiting, and analytics stakeholders to monitor quality and throughput.",
      "Maintain prompt, rubric, and escalation hygiene across human-in-the-loop workflows.",
    ],
    requirements: [
      "3+ years in product operations, business operations, or technical program delivery.",
      "Strong written communication and the ability to drive structured decisions across teams.",
      "Comfort working with AI tooling, workflow systems, and data-informed process improvement.",
      "Experience managing production-facing operations with high attention to detail.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-01T09:00:00.000Z"),
  },
  {
    title: "Forward Deployed Engineer",
    slug: "forward-deployed-engineer",
    team: "Customer Engineering",
    location: "San Francisco, CA",
    workModel: "Hybrid",
    level: "Senior",
    description:
      "Work directly with strategic customers to deploy workflow and AI systems into real operating environments. The role blends backend engineering, integration work, and on-the-ground product iteration.",
    responsibilities: [
      "Design and implement customer-specific workflow integrations against internal platform primitives.",
      "Lead technical discovery and convert business requirements into reliable production delivery plans.",
      "Debug operational issues across APIs, data pipelines, and automation layers.",
      "Feed product insights back into core platform abstractions and developer tooling.",
    ],
    requirements: [
      "5+ years of software engineering experience with strong API and systems fundamentals.",
      "Ability to work across product ambiguity and customer-facing delivery constraints.",
      "Experience shipping integration-heavy systems in cloud or SaaS environments.",
      "Strong ownership, debugging discipline, and clear communication with technical and non-technical partners.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-05T09:00:00.000Z"),
  },
  {
    title: "AI Operations Analyst",
    slug: "ai-operations-analyst",
    team: "Operations Strategy",
    location: "Remote - United States",
    workModel: "Remote",
    level: "Mid-Level",
    description:
      "Support the measurement and continuous improvement of AI-powered operating workflows. This role focuses on data quality, review queues, exception analysis, and operational reporting.",
    responsibilities: [
      "Monitor AI-assisted workflows for accuracy, latency, and exception trends.",
      "Build recurring reporting for recruiting operations, quality review, and SLA tracking.",
      "Investigate discrepancies between automated recommendations and human decisions.",
      "Coordinate with operations and engineering teams on process fixes and instrumentation gaps.",
    ],
    requirements: [
      "2+ years in operations analytics, business intelligence, or workflow operations.",
      "Comfort working with structured datasets, QA processes, and operational dashboards.",
      "Strong analytical judgment and the ability to identify root causes in messy processes.",
      "Experience collaborating closely with engineering or technical operations teams.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-10T09:00:00.000Z"),
  },
  {
    title: "Software Engineering Intern",
    slug: "software-engineering-intern",
    team: "Platform",
    location: "San Francisco, CA",
    workModel: "Hybrid",
    level: "Intern",
    description:
      "Summer internship building internal tools and APIs. Work with engineers on real features, code review, on-call shadowing, and shipping small end-to-end improvements.",
    responsibilities: [
      "Implement features and fixes in TypeScript and Python services.",
      "Write tests, participate in code review, and document runbooks.",
      "Collaborate with product and operations on workflow improvements.",
    ],
    requirements: [
      "Pursuing a CS or related degree; graduation 2026 or 2027.",
      "Coursework or projects in data structures, APIs, and SQL.",
      "Strong communication and curiosity about AI-assisted developer workflows.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-12T09:00:00.000Z"),
  },
  {
    title: "Product Intern",
    slug: "product-intern",
    team: "Product",
    location: "New York, NY",
    workModel: "Hybrid",
    level: "Intern",
    description:
      "Support roadmap execution, user research synthesis, and launch readiness for AI-powered hiring and operations products.",
    responsibilities: [
      "Draft specs, track metrics, and coordinate cross-functional check-ins.",
      "Synthesize user interviews and operational feedback into concise summaries.",
      "Partner with design and engineering on experiment design and rollout.",
    ],
    requirements: [
      "Currently enrolled in an undergraduate or graduate program.",
      "Strong written communication and structured problem solving.",
      "Interest in B2B SaaS, workflows, and responsible AI product decisions.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-12T10:00:00.000Z"),
  },
  {
    title: "New Grad Software Engineer",
    slug: "new-grad-software-engineer",
    team: "Core Engineering",
    location: "Remote - United States",
    workModel: "Remote",
    level: "New Grad",
    description:
      "Full-time role for recent graduates. Build reliable services, improve observability, and ship customer-facing improvements with mentorship from senior engineers.",
    responsibilities: [
      "Design, implement, and test backend and API features.",
      "Participate in on-call rotation with strong runbooks and escalation paths.",
      "Improve CI/CD, monitoring, and developer experience over time.",
    ],
    requirements: [
      "BS or MS in Computer Science or equivalent; graduation within the last 12 months.",
      "Experience with at least one modern language (e.g. TypeScript, Go, Python) and REST APIs.",
      "Comfort with SQL, Git, and collaborative software delivery.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-15T09:00:00.000Z"),
  },
  {
    title: "New Grad Data & Analytics",
    slug: "new-grad-data-analytics",
    team: "Data",
    location: "Austin, TX",
    workModel: "Hybrid",
    level: "New Grad",
    description:
      "Analyze hiring and product operations data, build dashboards, and support data quality for AI-assisted workflows.",
    responsibilities: [
      "Write SQL and build dashboards for recruiting and quality metrics.",
      "Investigate anomalies in pipelines and partner with ops on root cause analysis.",
      "Document metrics definitions and support ad hoc analytical requests.",
    ],
    requirements: [
      "Degree in a quantitative field; graduation within the last 12 months.",
      "Strong SQL and experience with spreadsheets or BI tools.",
      "Clear communication with technical and non-technical stakeholders.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-15T10:00:00.000Z"),
  },
  {
    title: "ML & AI Engineering Intern",
    slug: "ml-ai-engineering-intern",
    team: "Applied Research",
    location: "Remote - United States",
    workModel: "Remote",
    level: "Intern",
    description:
      "Research and prototype improvements to retrieval, evaluation, and safety checks for LLM-powered workflows. Partner with product engineering to ship experiments behind feature flags.",
    responsibilities: [
      "Run offline evals, analyze failure cases, and propose prompt or pipeline changes.",
      "Build small tools and notebooks to monitor quality and latency in staging.",
      "Document findings and present concise readouts to the broader team.",
    ],
    requirements: [
      "Strong Python; coursework or projects in ML, NLP, or information retrieval.",
      "Comfort reading papers and reproducing baselines in a codebase.",
      "Clear written communication and responsible mindset toward AI risk.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-16T09:00:00.000Z"),
  },
  {
    title: "Developer Relations Intern",
    slug: "developer-relations-intern",
    team: "Developer Experience",
    location: "San Francisco, CA",
    workModel: "Hybrid",
    level: "Intern",
    description:
      "Help developers succeed with our APIs and workflow SDKs: sample apps, docs, office hours, and community feedback loops.",
    responsibilities: [
      "Author tutorials, code samples, and changelog notes for API releases.",
      "Triage forum and support threads; reproduce bugs with minimal repros.",
      "Join customer calls to capture friction and feed the product roadmap.",
    ],
    requirements: [
      "Hands-on coding in TypeScript or Python; comfortable with REST APIs.",
      "Strong writing and empathy for developer audiences.",
      "Active listener who can turn feedback into actionable issues.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-16T10:00:00.000Z"),
  },
  {
    title: "New Grad Forward Deployed Engineer",
    slug: "new-grad-forward-deployed-engineer",
    team: "Customer Engineering",
    location: "New York, NY",
    workModel: "Hybrid",
    level: "New Grad",
    description:
      "Entry-level customer-facing engineering: deploy integrations, debug production issues, and translate customer needs into tickets the core team can ship.",
    responsibilities: [
      "Implement and test integrations against customer sandboxes.",
      "Support escalation queue with clear repro steps and log analysis.",
      "Partner with solutions architects on technical discovery sessions.",
    ],
    requirements: [
      "BS in CS or related; graduation within the last 12 months.",
      "Solid fundamentals in APIs, networking, and one systems language.",
      "Calm communicator under time pressure; willing to travel occasionally.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-17T09:00:00.000Z"),
  },
  {
    title: "New Grad Product Manager",
    slug: "new-grad-product-manager",
    team: "Product",
    location: "Seattle, WA",
    workModel: "Hybrid",
    level: "New Grad",
    description:
      "Rotational PM track for new grads: shipping features for hiring and ops workflows, metrics ownership, and cross-functional alignment.",
    responsibilities: [
      "Write crisp specs, acceptance criteria, and rollout plans.",
      "Define metrics, read dashboards, and drive weekly operating reviews.",
      "Coordinate design, eng, and GTM on launches and experiments.",
    ],
    requirements: [
      "Undergraduate or graduate degree; graduation within the last 12 months.",
      "Structured thinker with strong written communication.",
      "Interest in B2B SaaS, workflows, and responsible AI product decisions.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-17T10:00:00.000Z"),
  },
  {
    title: "Security Engineering Intern",
    slug: "security-engineering-intern",
    team: "Security",
    location: "Remote - United States",
    workModel: "Remote",
    level: "Intern",
    description:
      "Assist with security reviews, dependency scanning, and lightweight tooling for secrets detection and access hygiene.",
    responsibilities: [
      "Triage findings from SAST/DAST and dependency scanners.",
      "Help maintain runbooks for incident response drills.",
      "Build small automation scripts to improve visibility into configs.",
    ],
    requirements: [
      "Coursework or projects in systems, networking, or cryptography basics.",
      "Scripting in Python or Bash; curiosity about secure SDLC.",
      "Discretion and good judgment with sensitive information.",
    ],
    status: JobStatus.OPEN,
    openedAt: new Date("2026-03-18T09:00:00.000Z"),
  },
];
